<a href="https://colab.research.google.com/github/rajveer0104/MLlearning/blob/main/cross_fold_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the dependencies

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler


Importing the models

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [ ]:
heart=pd.read_csv('/content/heart.csv')

In [ ]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [ ]:
heart['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [ ]:
heart_2=heart.drop(columns='target',axis=1)
heart_2=heart_2.drop(columns='fbs',axis=1)
heart_2=heart_2.drop(columns='restecg',axis=1)
heart_2=heart_2.drop(columns='exang',axis=1)
heart_2=heart_2.drop(columns='slope',axis=1)
heart_2=heart_2.drop(columns='ca',axis=1)
heart_2=heart_2.drop(columns='thal',axis=1)
heart_2.head()
sclar=StandardScaler()
heart_2=sclar.fit_transform(heart_2)
heart_2=pd.DataFrame(heart_2)
heart_2.head()

0         1         2         3         4         5         6
0 -0.268437  0.661504 -0.915755 -0.377636 -0.659332  0.821321 -0.060888
1 -0.158157  0.661504 -0.915755  0.479107 -0.833861  0.255968  1.727137
2  1.716595  0.661504 -0.915755  0.764688 -1.396233 -1.048692  1.301417
3  0.724079  0.661504 -0.915755  0.936037 -0.833861  0.516900 -0.912329
4  0.834359 -1.511706 -0.915755  0.364875  0.930822 -1.874977  0.705408

In [ ]:
heart_features = heart.drop(columns='target').replace(0, np.nan)
heart_features = heart_features.fillna(heart_features.mean())

# Now replace the scaled features back, but keep the original target column
heart['age'] = heart_2[0]
heart['trestbps'] = heart_2[1]
heart['chol'] = heart_2[2]
heart['thalach'] = heart_2[3]
heart['oldpeak'] = heart_2[4]

# Make sure the target column is not affected by the imputation
heart['target'] = heart['target'].replace(np.nan, 0) # Revert the 0s back if they were changed

print(heart.head())

        age  sex  cp  trestbps      chol  fbs  restecg   thalach  exang  \
0 -0.268437    1   0  0.661504 -0.915755    0        1 -0.377636      0   
1 -0.158157    1   0  0.661504 -0.915755    1        0  0.479107      1   
2  1.716595    1   0  0.661504 -0.915755    0        1  0.764688      1   
3  0.724079    1   0  0.661504 -0.915755    0        1  0.936037      0   
4  0.834359    0   0 -1.511706 -0.915755    1        1  0.364875      0   

    oldpeak  slope  ca  thal  target  
0 -0.659332      2   2     3       0  
1 -0.833861      0   0     3       0  
2 -1.396233      0   0     3       0  
3 -0.833861      2   1     3       0  
4  0.930822      1   3     2       0  


In [ ]:
X=heart.drop(columns="target",axis=1)
Y=heart['target']

In [ ]:
print (X)
print(Y)

           age  sex  cp  trestbps      chol  fbs  restecg   thalach  exang  \
0    -0.268437    1   0  0.661504 -0.915755    0        1 -0.377636      0   
1    -0.158157    1   0  0.661504 -0.915755    1        0  0.479107      1   
2     1.716595    1   0  0.661504 -0.915755    0        1  0.764688      1   
3     0.724079    1   0  0.661504 -0.915755    0        1  0.936037      0   
4     0.834359    0   0 -1.511706 -0.915755    1        1  0.364875      0   
...        ...  ...  ..       ...       ...  ...      ...       ...    ...   
1020  0.503520    1   1  0.661504  0.055931    0        1  0.479107      1   
1021  0.613800    1   0  0.661504 -0.915755    0        0 -0.377636      1   
1022 -0.819834    1   0  0.661504 -0.915755    0        0 -1.234378      1   
1023 -0.488996    0   0 -1.511706 -0.915755    0        0 -1.234378      0   
1024 -0.047877    1   0  0.661504 -0.915755    0        1 -0.663216      0   

       oldpeak  slope  ca  thal  
0    -0.659332      2   2    

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=3)

In [ ]:
#list of models
list=[LogisticRegression(),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def model_train(list):
  for model in list:
    #training the model
    model.fit(X_train,Y_train)
    #predicting
    test_prediction=model.predict(X_test)
     #evaluating the accuracy
    accuracy=accuracy_score(Y_test,test_prediction)
    print("Prediction =",accuracy," when we use model",model)

In [ ]:
model_train(list)

Prediction = 0.8390243902439024  when we use model LogisticRegression()
Prediction = 0.8048780487804879  when we use model SVC(kernel='linear')
Prediction = 0.8585365853658536  when we use model KNeighborsClassifier()
Prediction = 1.0  when we use model RandomForestClassifier()


#Cross validation

logistic regression

In [ ]:
value_for_lr=cross_val_score(LogisticRegression(),X,Y,cv=5)
print(value_for_lr)

[0.87317073 0.81463415 0.82439024 0.82439024 0.76585366]


In [ ]:
mean=sum(value_for_lr)/len(value_for_lr)
print(mean)

0.8204878048780488


Support vector classifier

In [ ]:
value_for_svc= cross_val_score(SVC(kernel='linear'),X,Y,cv=5)
print(value_for_svc)
mean=sum(value_for_svc)/len(value_for_svc)
print(mean)

[0.85853659 0.7804878  0.81463415 0.82439024 0.75609756]
0.806829268292683


KNeigbours classifier


In [ ]:
value_for_knc=cross_val_score(KNeighborsClassifier(),X,Y,cv=5)
print(value_for_knc)
mean=sum(value_for_knc)/len(value_for_knc)
print(mean)

[0.85853659 0.84390244 0.80487805 0.87804878 0.83902439]
0.8448780487804879


In [ ]:
value_for_rfc=cross_val_score(RandomForestClassifier(),X,Y,cv=5)
print(value_for_rfc)
mean=sum(value_for_rfc)/len(value_for_rfc)
print(mean)

[1.         1.         1.         1.         0.98536585]
0.9970731707317073
