<a href="https://colab.research.google.com/github/rajveer0104/MLlearning/blob/main/grid_search_and_randomized_search_cv_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hyperparameter tuning               
1.Grid search cv             
2.randomized search cv

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
#loading the breast cancer dataset
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

In [ ]:
print(breast_cancer_dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [ ]:
dataset=pd.DataFrame(breast_cancer_dataset.data,columns=breast_cancer_dataset.feature_names)

In [ ]:
dataset.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
dataset['label']=breast_cancer_dataset.target

In [ ]:
dataset['label'].value_counts()

label
1    357
0    212
Name: count, dtype: int64

1- Beningn                
2- Malignant

In [ ]:
X=dataset.drop(columns='label',axis=1)
Y=dataset['label']

In [ ]:
print(X)
print(Y)

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]
0      0
1      0
2      0
3      0
4      0
      

In [ ]:
X=np.asarray(X)
Y=np.asarray(Y)

In [ ]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

#**Grid Search CV**   
Grid search is used to determine best parameters for our model


In [ ]:
model=SVC()

In [ ]:
#hyperparameters
parameters ={
    "kernel":['linear','poly','rbf','sigmoid'],

    'C':[1,5,10,20]
}

In [ ]:
#grid search
classifier=GridSearchCV(model,parameters,cv=5)

In [ ]:
#fitting data to model
classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([1.60574017e+00, 3.92174721e-03, 4.67786789e-03, 1.66077137e-02,
        3.10896831e+00, 5.45396805e-03, 4.13198471e-03, 1.35842323e-02,
        4.97580028e+00, 4.25720215e-03, 4.08282280e-03, 1.38099670e-02,
        7.71102066e+00, 4.35743332e-03, 4.16402817e-03, 1.35912418e-02]),
 'std_fit_time': array([6.12609149e-01, 1.15673166e-04, 3.14634364e-04, 2.43126653e-03,
        6.16262488e-01, 1.17202840e-03, 2.33094684e-04, 5.76155308e-04,
        1.08951680e+00, 2.19508038e-04, 1.03179077e-04, 8.39416655e-04,
        2.53460432e+00, 1.20357572e-04, 2.93281383e-04, 8.61225324e-04]),
 'mean_score_time': array([0.00158954, 0.00146956, 0.00225244, 0.00482821, 0.00137682,
        0.0017343 , 0.00177202, 0.00365086, 0.00134907, 0.0013494 ,
        0.00173683, 0.00371161, 0.00129051, 0.00128565, 0.00167365,
        0.00360065]),
 'std_score_time': array([2.63015613e-04, 4.68994011e-05, 5.68225668e-04, 7.31600997e-04,
        2.50193344e-04, 4.36610402e-04, 4.92073306e-

In [ ]:
#best parameters
best=classifier.best_params_
print(best)
#best accuracy
best_accuracy=classifier.best_score_
print(best_accuracy)

{'C': 10, 'kernel': 'linear'}
0.9525694767893185


In [ ]:
#loading result to pandas dataframe
results=pd.DataFrame(classifier.cv_results_)

In [ ]:
results.head()

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       1.605740      0.612609  ...        0.018689                4
1       0.003922      0.000116  ...        0.039382               12
2       0.004678      0.000315  ...        0.035444               11
3       0.016608      0.002431  ...        0.050253               13
4       3.108968      0.616262  ...        0.016216                2

[5 rows x 15 columns]

In [ ]:
grid_search_result = results[['param_C','param_kernel','mean_test_score']]

In [ ]:
print(grid_search_result)

    param_C param_kernel  mean_test_score
0         1       linear         0.945536
1         1         poly         0.908663
2         1          rbf         0.912172
3         1      sigmoid         0.460441
4         5       linear         0.950815
5         5         poly         0.922729
6         5          rbf         0.931501
7         5      sigmoid         0.411178
8        10       linear         0.952569
9        10         poly         0.920975
10       10          rbf         0.922714
11       10      sigmoid         0.402391
12       20       linear         0.949061
13       20         poly         0.919221
14       20          rbf         0.920944
15       20      sigmoid         0.398867


#Randomized search cv

In [ ]:
model=SVC()
#hyperparameters
parameters ={
    "kernel":['linear','poly','rbf','sigmoid'],

    'C':[1,5,10,20]
}

In [ ]:
#randomized search
classifier=RandomizedSearchCV(model,parameters,cv=5)

In [ ]:
classifier.fit(X,Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [ ]:
classifier.cv_results_
#best parameters
best=classifier.best_params_
print(best)
#best accuracy
best_accuracy=classifier.best_score_
print(best_accuracy)

{'kernel': 'linear', 'C': 20}
0.9490607048594939


In [ ]:
#loading result to pandas dataframe
results=pd.DataFrame(classifier.cv_results_)
results.head()

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.005030      0.000548  ...        0.027879                4
1       0.004739      0.000217  ...        0.027300                7
2       0.005080      0.000687  ...        0.035444                8
3       1.836561      1.257601  ...        0.018689                2
4       0.003932      0.000285  ...        0.023689                3

[5 rows x 15 columns]

In [ ]:
randomized_search_result = results[['param_C','param_kernel','mean_test_score']]
print(randomized_search_result)

   param_C param_kernel  mean_test_score
0       10          rbf         0.922714
1       20         poly         0.919221
2        1          rbf         0.912172
3        1       linear         0.945536
4        5         poly         0.922729
5       10         poly         0.920975
6        5      sigmoid         0.411178
7       20       linear         0.949061
8       20          rbf         0.920944
9       10      sigmoid         0.402391
