<a href="https://colab.research.google.com/github/rajveer0104/MLlearning/blob/main/schol_elig.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df=pd.read_excel('/content/dataset_combined.xlsx')

In [ ]:
df.head()

Name Education Qualification  \
0  INSPIRE Scholarship 2022-23 ? Scholarship for ...           Undergraduate   
1  INSPIRE Scholarship 2022-23 ? Scholarship for ...           Undergraduate   
2  INSPIRE Scholarship 2022-23 ? Scholarship for ...           Undergraduate   
3  INSPIRE Scholarship 2022-23 ? Scholarship for ...           Undergraduate   
4  INSPIRE Scholarship 2022-23 ? Scholarship for ...           Undergraduate   

  Gender Community   Religion Exservice-men Disability Sports  \
0   Male   General      Hindu           Yes        Yes    Yes   
1   Male   General      Hindu           Yes        Yes     No   
2   Male   General     Muslim           Yes        Yes    Yes   
3   Male   General     Muslim           Yes        Yes     No   
4   Male   General  Chirstian           Yes        Yes    Yes   

  Annual-Percentage     Income India  Outcome  
0            90-100  Upto 1.5L    In        1  
1            90-100  Upto 1.5L    In        1  
2            90-100  Upto 1.5L    In        1  
3            90-100  Upto 1.5L    In        1  
4            90-100  Upto 1.5L    In        1

In [ ]:
df['Outcome'].value_counts()

Outcome
0    212992
1     32768
Name: count, dtype: int64

In [ ]:
X=df.drop(columns='Outcome',axis=1)
Y=df['Outcome']

In [ ]:
# Install imbalanced-learn if not already installed
# pip install imbalanced-learn

from imblearn.under_sampling import RandomUnderSampler

# X = Features, y = Labels (ensure these are pandas DataFrame/Series or numpy arrays)
rus = RandomUnderSampler(sampling_strategy='majority', random_state=42)
X, Y = rus.fit_resample(X, Y)

print("Original class distribution:", dict(zip(*np.unique(Y, return_counts=True))))
#print("Resampled class distribution:", dict(zip(*np.unique(y_resampled, return_counts=True))))


Original class distribution: {np.int64(0): np.int64(32768), np.int64(1): np.int64(32768)}


In [ ]:
from sklearn.linear_model import LogisticRegression
X.drop(columns='Name',axis=1,inplace=True)

In [ ]:
lr=LogisticRegression()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:

X['Education Qualification']=le.fit_transform(X['Education Qualification'])
X['Gender']=le.fit_transform(X['Gender'])
X['Community']=le.fit_transform(X['Community'])
X.drop(columns='Religion',axis=1,inplace=True)

In [ ]:
X['Annual-Percentage']=le.fit_transform(X['Annual-Percentage'])
X['Income']=le.fit_transform(X['Income'])
X['Exservice-men']=le.fit_transform(X['Exservice-men'])
X['Disability']=le.fit_transform(X['Disability'])
X['Gender']=le.fit_transform(X['Gender'])
X['Sports']=le.fit_transform(X['Sports'])
X['India']=le.fit_transform(X['India'])


In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
X.dtypes

Education Qualification    int64
Gender                     int64
Community                  int64
Exservice-men              int64
Disability                 int64
Sports                     int64
Annual-Percentage          int64
Income                     int64
India                      int64
dtype: object

In [ ]:
Y.dtypes

dtype('int64')

In [ ]:
Y_train.shape

(52428,)

In [ ]:
X.head()

Education Qualification  Gender  Community  Exservice-men  Disability  \
161414                        1       1          2              1           1   
180660                        1       1          2              1           0   
54251                         2       0          1              0           1   
157379                        0       0          3              0           1   
166034                        1       1          0              1           1   

        Sports  Annual-Percentage  Income  India  
161414       1                  1       3      0  
180660       1                  2       2      0  
54251        0                  3       1      1  
157379       0                  2       3      0  
166034       1                  0       0      0

In [ ]:
lr.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
lr.score(X_test,Y_test)

0.7332163564235581

In [ ]:
lr.score(X_train,Y_train)

0.7313076981765468

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
matrix=confusion_matrix(Y_test,lr.predict(X_test))

In [ ]:
matrix

array([[4023, 2531],
       [ 966, 5588]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
tr=DecisionTreeClassifier()

In [ ]:
tr.fit(X_train,Y_train)

DecisionTreeClassifier()

In [ ]:
tr.score(X_test,Y_test)

0.7136100091547147

In [ ]:
tr.score(X_train,Y_train)

0.7714961470969711

In [ ]:
confusion_matrix(Y_test,tr.predict(X_test))

array([[4493, 2061],
       [1693, 4861]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)

RandomForestClassifier()

In [ ]:
rf.score(X_test,Y_test)

0.7140677448886177

In [ ]:
confusion_matrix(Y_test,rf.predict(X_test))

array([[4326, 2228],
       [1520, 5034]])

In [ ]:


from sklearn.neighbors import KNeighborsClassifier

In [ ]:
kn=KNeighborsClassifier()
kn.fit(X_train,Y_train)


KNeighborsClassifier()

In [ ]:
kn.score(X_test,Y_test)

0.6996490692706744

In [ ]:
confusion_matrix(Y_test,kn.predict(X_test))

array([[4285, 2269],
       [1668, 4886]])

In [ ]:
df['Outcome'].value_counts()

Outcome
0    212992
1     32768
Name: count, dtype: int64

In [ ]:
Y.value_counts()

Outcome
0    32768
1    32768
Name: count, dtype: int64

In [ ]:
kn

KNeighborsClassifier()

In [ ]:
import pickle
with open('schol.pkl','wb') as f:
  pickle.dump(kn,f)

In [ ]:
X.shape

(65536, 9)

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
mod=keras.Sequential([
    keras.layers.Dense(9,input_shape=(9,),activation='relu'),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])
mod.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
mod.fit(X_train,Y_train,epochs=50)

Epoch 1/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.6869 - loss: 0.5797
Epoch 2/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7392 - loss: 0.5106
Epoch 3/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7455 - loss: 0.4981
Epoch 4/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7454 - loss: 0.4976
Epoch 5/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7451 - loss: 0.4956
Epoch 6/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7511 - loss: 0.4905
Epoch 7/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7534 - loss: 0.4889
Epoch 8/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7541 - loss: 0.4868
Epoch 9/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7553 - loss: 0.4878
Epoch 10/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7507 - loss: 0.4903
Epoch 11/50
1639/1639 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7515 - loss: 0.4865
Epoch 12/50
1639/1639 ━━━━━━━━

In [ ]:
con=confusion_matrix(Y_test,mod.predict(X_test))

410/410 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


ValueError: Classification metrics can't handle a mix of binary and continuous targets